[project]
name = "fastapiprojecti"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "sarelo.ek", email = "zh050208@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "pydantic>=2.13.5",
    "sqlalchemy>=2.0.53",
    "uvicorn>=0.53.0",
]

[project.scripts]
fastapiprojecti = "fastapiprojecti:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
